openapi: 3.1.0
info:
  version: 1.0.0
  title: Tasteorama
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Recipes Book App.
tags:
  - name: Auth
    description: Auth operations.
  - name: Categories
    description: Operations about categories.
  - name: Ingredients
    description: Operations about ingredients.
  - name: Recipes
    description: Operations about recipes.
  - name: Users
    description: Operations about users.
servers:
  - url: https://backendrepo-ormv.onrender.com
paths:
  /api/auth/register:
    post:
      $ref: '../swagger/path/auth/register/post.yaml'
  /api/auth/login:
    post:
      $ref: ../swagger/path/auth/login/post.yaml
  /api/auth/logout:
    post:
      $ref: ../swagger/path/auth/logout/post.yaml
  /api/auth/refresh:
    post:
      $ref: ../swagger/path/auth/refresh/post.yaml

  /api/users/current:
    get:
      $ref: ../swagger/path/users/current/get.yaml
  /api/users/favorites:
    get:
      $ref: ../swagger/path/users/favorites/get.yaml
  /api/users/favorites/{recipeId}:
    post:
      $ref: ../swagger/path/users/favorites/{recipeId}/post.yaml
    delete:
      $ref: ../swagger/path/users/favorites/{recipeId}/delete.yaml
  /api/users/own:
    get:
      $ref: ../swagger/path/users/own/get.yaml

  /api/recipes:
    get:
      $ref: ../swagger/path/recipes/get.yaml
    post:
      $ref: ../swagger/path/recipes/post.yaml
  /api/recipes/{recipeId}:
    get:
      $ref: ../swagger/path/recipes/{recipeId}/get.yaml

  /api/categories:
    get:
      $ref: ../swagger/path/categories/get.yaml

  /api/ingredients:
    get:
      $ref: ../swagger/path/ingredients/get.yaml
components:
  # schemas:
  #   UserRegister:
  #     $ref: ../swagger/components/schemas/userRegister.yaml
  #   UserLogin:
  #     $ref: ../swagger/components/schemas/userLogin.yaml
  #   CreateRecipe:
  #     $ref: ../swagger/components/schemas/recipe.yaml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
